name: 'Scala Dependency Graph Action'
description: 'Submits the dependency graph of your Scala build to the Github Submission API'
author: 'The Scala Center'
branding:
  icon: 'package'
  color: '#1a84ac'
inputs:
  base-dir:
    description: "The relative path of the base directory of your Scala build."
    required: false
    default: ''
  build-tool:
    description: "The build tool used for your workspace."
    required: false
    default: ''
  projects:
    description: "A list of space-separated names of projects from your build. The action will publish the graph of these projects only. If unspecified, the action will detect all the projects of the build."
    required: false
    default: ''
  scala-versions:
    description: "A list of space-separated versions of Scala, that are declared in your build. The action will publish the graph on these Scala versions only. If unspecified, the action will detect all the Scala versions of the build."
    required: false
    default: ''
  token:
    description: "GitHub Personal Access Token (PAT). Defaults to PAT provided by Action runner."
    required: false
    default: ${{ github.token }}
  plugin-version:
    description: "Override the version of the (mill/sbt) plugin that is used internally."
    required: false
    default: ''
runs:
  using: 'node16'
  main: 'dist/index.js'
